### ISSUE TITLE
IMAP MailBox Configuration Edit - NPE at select Folder with incorrect connection

### ISSUE THREAD

**Issue by mariodavid** [cuba-platform/imap-addon#4]
When creating a IMAP configuration and hit "Select Folder" before setting the proper connection, a NPE is thrown:

```
java.lang.NullPointerException
	at com.haulmont.addon.imap.core.ImapHelper.getStore(ImapHelper.java:132)
	at com.haulmont.addon.imap.api.Imap.fetchFolders(Imap.java:55)
	at com.haulmont.addon.imap.service.ImapAPIServiceBean.fetchFolders(ImapAPIServiceBean.java:38)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:333)
	at...
```

Selection of folders should probably be enabled after a successful connection could be established.

**Comment by mariodavid** [comment]
Attached you'll find an example:
![imap-mailbox-config-npe](https://user-images.githubusercontent.com/817400/38044306-a31a0be8-32b9-11e8-8252-e9415de6d159.gif)

**Comment by shmelev-haulmont** [comment]
Mario,

Please see #2

Thanks,
Maksim
