### ISSUE TITLE
Fix folder names localization

### ISSUE THREAD

**Issue by smianna** [cuba-platform/imap-addon#46]
**Steps to reproduce:**
1. Open Menu: Administration → IMAP → IMAP Configuration.
2. Create a configuration (it is required to connect to a mailbox that has folder names in Cyrillic).
3. Click 'Connect'.

**Expected Result:** All folder names are localized properly.
**Actual Result:** 
![image](https://user-images.githubusercontent.com/38000666/40305650-695b8bd4-5d0c-11e8-9a5a-68cd469f90cd.png)

**Comment by smianna** [comment]
Verified.

**Comment by smianna** [comment]
The following error occurs after saving an IMAP Configuration:
```
16:52:20.609 ERROR c.haulmont.addon.imap.sync.ImapSync - Full sync failed
java.util.concurrent.ExecutionException: com.haulmont.addon.imap.exception.ImapException: error performing task 'fetch new messages' for folder with key 'imap.yandex.ru:993[user:nesmianas][╨б╨┐╨░╨╝]' caused by: [javax.mail.MessagingException]C3 BAD [CLIENTBUG] LIST Folder encoding error. sc=KqMBoD0fqOs1_261252_31j
        at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357) ~[na:1.8.0_171]
        at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1915) ~[na:1.8.0_171]
        at com.haulmont.addon.imap.sync.ImapSync.lambda$executeFullSyncTasks$2(ImapSync.java:157) ~[imap-core-0.1-SNAPSHOT.jar:na]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_171]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_171]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_171]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_171]
        at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_171]
Caused by: com.haulmont.addon.imap.exception.ImapException: error performing task 'fetch new messages' for folder with key 'imap.yandex.ru:993[user:nesmianas][╨б╨┐╨░╨╝]' caused by: [javax.mail.MessagingException]C3 BAD [CLIENTBUG] LIST Folder encoding error. sc=KqMBoD0fqOs1_261252_31j
        at com.haulmont.addon.imap.core.ImapHelper.doWithFolder(ImapHelper.java:159) ~[imap-core-0.1-SNAPSHOT.jar:na]
        at com.haulmont.addon.imap.core.ImapHelper.doWithFolder(ImapHelper.java:138) ~[imap-core-0.1-SNAPSHOT.jar:na]
        at com.haulmont.addon.imap.sync.events.standard.ImapNewMessagesEvents.generate(ImapNewMessagesEvents.java:69) ~[imap-core-0.1-SNAPSHOT.jar:na]
        at com.haulmont.addon.imap.sync.events.standard.ImapStandardEventsGenerator.generateForNewMessages(ImapStandardEventsGenerator.java:34) ~[imap-core-0.1-SNAPSHOT.jar:na]
        at com.haulmont.addon.imap.sync.events.ImapEvents.handleNewMessages(ImapEvents.java:49) ~[imap-core-0.1-SNAPSHOT.jar:na]
        at com.haulmont.addon.imap.sync.ImapSync.lambda$folderFullSyncTask$4(ImapSync.java:180) ~[imap-core-0.1-SNAPSHOT.jar:na]
        at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1626) ~[na:1.8.0_171]
        ... 3 common frames omitted
16:52:21.025 ERROR c.haulmont.addon.imap.sync.ImapSync - Full sync failed
java.util.concurrent.ExecutionException: com.haulmont.addon.imap.exception.ImapException: error performing task 'fetch new messages' for folder with key 'imap.yandex.ru:993[user:nesmianas][╨з╨╡╤А╨╜╨╛╨▓╨╕╨║╨╕]' caused by: [javax.mail.MessagingException]D3 BAD [CLIENTBUG] LIST Folder encoding error. sc=LqMTTw2AYmI1_261252_34j
        at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357) ~[na:1.8.0_171]
        at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1915) ~[na:1.8.0_171]
        at com.haulmont.addon.imap.sync.ImapSync.lambda$executeFullSyncTasks$2(ImapSync.java:157) ~[imap-core-0.1-SNAPSHOT.jar:na]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_171]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_171]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_171]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_171]
        at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_171]
Caused by: com.haulmont.addon.imap.exception.ImapException: error performing task 'fetch new messages' for folder with key 'imap.yandex.ru:993[user:nesmianas][╨з╨╡╤А╨╜╨╛╨▓╨╕╨║╨╕]' caused by: [javax.mail.MessagingException]D3 BAD [CLIENTBUG] LIST Folder encoding error. sc=LqMTTw2AYmI1_261252_34j
        at com.haulmont.addon.imap.core.ImapHelper.doWithFolder(ImapHelper.java:159) ~[imap-core-0.1-SNAPSHOT.jar:na]
        at com.haulmont.addon.imap.core.ImapHelper.doWithFolder(ImapHelper.java:138) ~[imap-core-0.1-SNAPSHOT.jar:na]
        at com.haulmont.addon.imap.sync.events.standard.ImapNewMessagesEvents.generate(ImapNewMessagesEvents.java:69) ~[imap-core-0.1-SNAPSHOT.jar:na]
        at com.haulmont.addon.imap.sync.events.standard.ImapStandardEventsGenerator.generateForNewMessages(ImapStandardEventsGenerator.java:34) ~[imap-core-0.1-SNAPSHOT.jar:na]
        at com.haulmont.addon.imap.sync.events.ImapEvents.handleNewMessages(ImapEvents.java:49) ~[imap-core-0.1-SNAPSHOT.jar:na]
        at com.haulmont.addon.imap.sync.ImapSync.lambda$folderFullSyncTask$4(ImapSync.java:180) ~[imap-core-0.1-SNAPSHOT.jar:na]
        at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1626) ~[na:1.8.0_171]
        ... 3 common frames omitted
16:52:21.547 ERROR c.haulmont.addon.imap.sync.ImapSync - Full sync failed
java.util.concurrent.ExecutionException: com.haulmont.addon.imap.exception.ImapException: error performing task 'fetch new messages' for folder with key 'imap.yandex.ru:993[user:nesmianas][╨г╨┤╨░╨╗╨╡╨╜╨╜╤Л╨╡]' caused by: [javax.mail.MessagingException]E3 BAD [CLIENTBUG] LIST Folder encoding error. sc=LqMgex0H4qM1_261252_3j
        at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357) ~[na:1.8.0_171]
        at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1915) ~[na:1.8.0_171]
        at com.haulmont.addon.imap.sync.ImapSync.lambda$executeFullSyncTasks$2(ImapSync.java:157) ~[imap-core-0.1-SNAPSHOT.jar:na]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_171]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_171]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_171]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_171]
        at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_171]
Caused by: com.haulmont.addon.imap.exception.ImapException: error performing task 'fetch new messages' for folder with key 'imap.yandex.ru:993[user:nesmianas][╨г╨┤╨░╨╗╨╡╨╜╨╜╤Л╨╡]' caused by: [javax.mail.MessagingException]E3 BAD [CLIENTBUG] LIST Folder encoding error. sc=LqMgex0H4qM1_261252_3j
        at com.haulmont.addon.imap.core.ImapHelper.doWithFolder(ImapHelper.java:159) ~[imap-core-0.1-SNAPSHOT.jar:na]
        at com.haulmont.addon.imap.core.ImapHelper.doWithFolder(ImapHelper.java:138) ~[imap-core-0.1-SNAPSHOT.jar:na]
        at com.haulmont.addon.imap.sync.events.standard.ImapNewMessagesEvents.generate(ImapNewMessagesEvents.java:69) ~[imap-core-0.1-SNAPSHOT.jar:na]
        at com.haulmont.addon.imap.sync.events.standard.ImapStandardEventsGenerator.generateForNewMessages(ImapStandardEventsGenerator.java:34) ~[imap-core-0.1-SNAPSHOT.jar:na]
        at com.haulmont.addon.imap.sync.events.ImapEvents.handleNewMessages(ImapEvents.java:49) ~[imap-core-0.1-SNAPSHOT.jar:na]
        at com.haulmont.addon.imap.sync.ImapSync.lambda$folderFullSyncTask$4(ImapSync.java:180) ~[imap-core-0.1-SNAPSHOT.jar:na]
        at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1626) ~[na:1.8.0_171]
        ... 3 common frames omitted
16:52:22.183 ERROR c.haulmont.addon.imap.sync.ImapSync - Full sync failed
java.util.concurrent.ExecutionException: com.haulmont.addon.imap.exception.ImapException: error performing task 'fetch new messages' for folder with key 'imap.yandex.ru:993[user:nesmianas][╨Ю╤В╨┐╤А╨░╨▓╨╗╨╡╨╜╨╜╤Л╨╡]' caused by: [javax.mail.MessagingException]F3 BAD [CLIENTBUG] LIST Folder encoding error. sc=MqMTLx0LeOs1_261252_7o
        at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357) ~[na:1.8.0_171]
        at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1915) ~[na:1.8.0_171]
        at com.haulmont.addon.imap.sync.ImapSync.lambda$executeFullSyncTasks$2(ImapSync.java:157) ~[imap-core-0.1-SNAPSHOT.jar:na]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_171]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_171]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_171]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_171]
        at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_171]
Caused by: com.haulmont.addon.imap.exception.ImapException: error performing task 'fetch new messages' for folder with key 'imap.yandex.ru:993[user:nesmianas][╨Ю╤В╨┐╤А╨░╨▓╨╗╨╡╨╜╨╜╤Л╨╡]' caused by: [javax.mail.MessagingException]F3 BAD [CLIENTBUG] LIST Folder encoding error. sc=MqMTLx0LeOs1_261252_7o
        at com.haulmont.addon.imap.core.ImapHelper.doWithFolder(ImapHelper.java:159) ~[imap-core-0.1-SNAPSHOT.jar:na]
        at com.haulmont.addon.imap.core.ImapHelper.doWithFolder(ImapHelper.java:138) ~[imap-core-0.1-SNAPSHOT.jar:na]
        at com.haulmont.addon.imap.sync.events.standard.ImapNewMessagesEvents.generate(ImapNewMessagesEvents.java:69) ~[imap-core-0.1-SNAPSHOT.jar:na]
        at com.haulmont.addon.imap.sync.events.standard.ImapStandardEventsGenerator.generateForNewMessages(ImapStandardEventsGenerator.java:34) ~[imap-core-0.1-SNAPSHOT.jar:na]
        at com.haulmont.addon.imap.sync.events.ImapEvents.handleNewMessages(ImapEvents.java:49) ~[imap-core-0.1-SNAPSHOT.jar:na]
        at com.haulmont.addon.imap.sync.ImapSync.lambda$folderFullSyncTask$4(ImapSync.java:180) ~[imap-core-0.1-SNAPSHOT.jar:na]
        at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1626) ~[na:1.8.0_171]
        ... 3 common frames omitted
16:52:22.655 ERROR c.haulmont.addon.imap.sync.ImapSync - Full sync failed
java.util.concurrent.ExecutionException: com.haulmont.addon.imap.exception.ImapException: error performing task 'fetch new messages' for folder with key 'imap.yandex.ru:993[user:nesmianas][╨Ш╤Б╤Е╨╛╨┤╤П╤Й╨╕╨╡]' caused by: [javax.mail.MessagingException]G3 BAD [CLIENTBUG] LIST Folder encoding error. sc=NqM41K0inqM1_261252_61j
        at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357) ~[na:1.8.0_171]
        at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1915) ~[na:1.8.0_171]
        at com.haulmont.addon.imap.sync.ImapSync.lambda$executeFullSyncTasks$2(ImapSync.java:157) ~[imap-core-0.1-SNAPSHOT.jar:na]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_171]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_171]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_171]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_171]
        at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_171]
Caused by: com.haulmont.addon.imap.exception.ImapException: error performing task 'fetch new messages' for folder with key 'imap.yandex.ru:993[user:nesmianas][╨Ш╤Б╤Е╨╛╨┤╤П╤Й╨╕╨╡]' caused by: [javax.mail.MessagingException]G3 BAD [CLIENTBUG] LIST Folder encoding error. sc=NqM41K0inqM1_261252_61j
        at com.haulmont.addon.imap.core.ImapHelper.doWithFolder(ImapHelper.java:159) ~[imap-core-0.1-SNAPSHOT.jar:na]
        at com.haulmont.addon.imap.core.ImapHelper.doWithFolder(ImapHelper.java:138) ~[imap-core-0.1-SNAPSHOT.jar:na]
        at com.haulmont.addon.imap.sync.events.standard.ImapNewMessagesEvents.generate(ImapNewMessagesEvents.java:69) ~[imap-core-0.1-SNAPSHOT.jar:na]
        at com.haulmont.addon.imap.sync.events.standard.ImapStandardEventsGenerator.generateForNewMessages(ImapStandardEventsGenerator.java:34) ~[imap-core-0.1-SNAPSHOT.jar:na]
        at com.haulmont.addon.imap.sync.events.ImapEvents.handleNewMessages(ImapEvents.java:49) ~[imap-core-0.1-SNAPSHOT.jar:na]
        at com.haulmont.addon.imap.sync.ImapSync.lambda$folderFullSyncTask$4(ImapSync.java:180) ~[imap-core-0.1-SNAPSHOT.jar:na]
        at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1626) ~[na:1.8.0_171]
        ... 3 common frames omitted
16:52:27.780 ERROR c.haulmont.addon.imap.sync.ImapSync - Full sync failed
java.util.concurrent.ExecutionException: com.haulmont.addon.imap.exception.ImapException: [javax.mail.FolderClosedException]javax.mail.FolderClosedException
        at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357) ~[na:1.8.0_171]
        at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1915) ~[na:1.8.0_171]
        at com.haulmont.addon.imap.sync.ImapSync.lambda$executeFullSyncTasks$2(ImapSync.java:157) ~[imap-core-0.1-SNAPSHOT.jar:na]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_171]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_171]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_171]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_171]
        at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_171]
Caused by: com.haulmont.addon.imap.exception.ImapException: [javax.mail.FolderClosedException]javax.mail.FolderClosedException
        at com.haulmont.addon.imap.sync.events.standard.ImapNewMessagesEvents.generate(ImapNewMessagesEvents.java:115) ~[imap-core-0.1-SNAPSHOT.jar:na]
        at com.haulmont.addon.imap.sync.events.standard.ImapNewMessagesEvents.lambda$generate$0(ImapNewMessagesEvents.java:72) ~[imap-core-0.1-SNAPSHOT.jar:na]
        at com.haulmont.addon.imap.core.ImapHelper.doWithFolder(ImapHelper.java:154) ~[imap-core-0.1-SNAPSHOT.jar:na]
        at com.haulmont.addon.imap.core.ImapHelper.doWithFolder(ImapHelper.java:138) ~[imap-core-0.1-SNAPSHOT.jar:na]
        at com.haulmont.addon.imap.sync.events.standard.ImapNewMessagesEvents.generate(ImapNewMessagesEvents.java:69) ~[imap-core-0.1-SNAPSHOT.jar:na]
        at com.haulmont.addon.imap.sync.events.standard.ImapStandardEventsGenerator.generateForNewMessages(ImapStandardEventsGenerator.java:34) ~[imap-core-0.1-SNAPSHOT.jar:na]
        at com.haulmont.addon.imap.sync.events.ImapEvents.handleNewMessages(ImapEvents.java:49) ~[imap-core-0.1-SNAPSHOT.jar:na]
        at com.haulmont.addon.imap.sync.ImapSync.lambda$folderFullSyncTask$4(ImapSync.java:180) ~[imap-core-0.1-SNAPSHOT.jar:na]
        at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1626) ~[na:1.8.0_171]
        ... 3 common frames omitted
```

**Comment by smianna** [comment]
Verified
