### ISSUE TITLE
IllegalStateException when opening an email

### ISSUE THREAD

**Issue by smianna** [cuba-platform/imap-addon#48]
**Steps to reproduce:**
1. Open Menu: Administration → IMAP → IMAP Message Browser
2. Select an email
3. Click *View*

**Expected Result:**
Details about the selected email are downloaded.

**Actual Result:** 
```
17:11:55.743 ERROR c.h.c.w.g.e.impl.WebBackgroundWorker - Unhandled exception in background task
java.util.concurrent.ExecutionException: com.haulmont.cuba.core.global.RemoteException:
---
java.lang.IllegalStateException: Not connected
        at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[na:1.8.0_171]
        at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[na:1.8.0_171]
        at com.haulmont.cuba.web.gui.executors.impl.WebBackgroundWorker$WebTaskExecutor.handleDone(WebBackgroundWorker.java:273) ~[cuba-web-6.8.8.jar:6.8.8]
        at com.haulmont.cuba.web.gui.executors.impl.WebBackgroundWorker$WebTaskExecutor$1.lambda$done$0(WebBackgroundWorker.java:187) [cuba-web-6.8.8.jar:6.8.8]
        at com.vaadin.ui.UI.accessSynchronously(UI.java:1392) ~[vaadin-server-7.7.13.cuba.9.jar:7.7.13.cuba.9]
        at com.vaadin.ui.UI$4.run(UI.java:1458) ~[vaadin-server-7.7.13.cuba.9.jar:7.7.13.cuba.9]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_171]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_171]
        at com.vaadin.server.VaadinService.runPendingAccessTasks(VaadinService.java:1861) ~[vaadin-server-7.7.13.cuba.9.jar:7.7.13.cuba.9]
        at com.vaadin.server.VaadinSession.unlock(VaadinSession.java:994) ~[vaadin-server-7.7.13.cuba.9.jar:7.7.13.cuba.9]
        at com.vaadin.server.VaadinService.ensureAccessQueuePurged(VaadinService.java:1824) ~[vaadin-server-7.7.13.cuba.9.jar:7.7.13.cuba.9]
        at com.vaadin.server.VaadinService.accessSession(VaadinService.java:1790) ~[vaadin-server-7.7.13.cuba.9.jar:7.7.13.cuba.9]
        at com.vaadin.server.VaadinSession.access(VaadinSession.java:1399) ~[vaadin-server-7.7.13.cuba.9.jar:7.7.13.cuba.9]
        at com.vaadin.ui.UI.access(UI.java:1455) ~[vaadin-server-7.7.13.cuba.9.jar:7.7.13.cuba.9]
        at com.haulmont.cuba.web.gui.executors.impl.WebBackgroundWorker$WebTaskExecutor$1.done(WebBackgroundWorker.java:186) [cuba-web-6.8.8.jar:6.8.8]
        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:384) ~[na:1.8.0_171]
        at java.util.concurrent.FutureTask.setException(FutureTask.java:251) ~[na:1.8.0_171]
        at java.util.concurrent.FutureTask.run(FutureTask.java:271) ~[na:1.8.0_171]
        at com.haulmont.cuba.web.gui.executors.impl.WebBackgroundWorker$WebTaskExecutor.lambda$startExecution$1(WebBackgroundWorker.java:371) ~[cuba-web-6.8.8.jar:6.8.8]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_171]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_171]
        at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_171]
Caused by: com.haulmont.cuba.core.global.RemoteException: Not connected
        at com.haulmont.cuba.core.sys.ServiceInterceptor.aroundInvoke(ServiceInterceptor.java:129) ~[na:na]
        at sun.reflect.GeneratedMethodAccessor184.invoke(Unknown Source) ~[na:na]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_171]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_171]
        at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:629) ~[spring-aop-4.3.12.RELEASE.jar:4.3.12.RELEASE]
        at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:618) ~[spring-aop-4.3.12.RELEASE.jar:4.3.12.RELEASE]
        at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:70) ~[spring-aop-4.3.12.RELEASE.jar:4.3.12.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:168) ~[spring-aop-4.3.12.RELEASE.jar:4.3.12.RELEASE]
        at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92) ~[spring-aop-4.3.12.RELEASE.jar:4.3.12.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) ~[spring-aop-4.3.12.RELEASE.jar:4.3.12.RELEASE]
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:213) ~[spring-aop-4.3.12.RELEASE.jar:4.3.12.RELEASE]
        at com.sun.proxy.$Proxy268.fetchAttachments(Unknown Source) ~[na:na]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_171]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_171]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_171]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_171]
        at com.haulmont.cuba.core.sys.remoting.LocalServiceInvokerImpl.invoke(LocalServiceInvokerImpl.java:94) ~[na:na]
        at com.haulmont.cuba.web.sys.remoting.LocalServiceProxy$LocalServiceInvocationHandler.invoke(LocalServiceProxy.java:154) ~[cuba-web-6.8.8.jar:6.8.8]
        at com.sun.proxy.$Proxy61.fetchAttachments(Unknown Source) ~[na:na]
        at com.haulmont.addon.imap.web.imapmessage.ImapMessageEdit$InitAttachmentTask.run(ImapMessageEdit.java:123) ~[imap-web-0.1-SNAPSHOT.jar:na]
        at com.haulmont.addon.imap.web.imapmessage.ImapMessageEdit$InitAttachmentTask.run(ImapMessageEdit.java:113) ~[imap-web-0.1-SNAPSHOT.jar:na]
        at com.haulmont.cuba.web.gui.executors.impl.WebBackgroundWorker$WebTaskExecutor.call(WebBackgroundWorker.java:205) ~[cuba-web-6.8.8.jar:6.8.8]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_171]
        ... 4 common frames omitted
```

**Comment by smianna** [comment]
Verified.
