### ISSUE TITLE
Upgrade CUBA platform to 6.9 version

### ISSUE THREAD

**Issue by zaharchenko-evgeny** [cuba-platform/imap-addon#51]

**Comment by smianna** [comment]
Currently, if the component is added to the application with the platform version 6.9.x, the following exception occurs after creating an IMAP configuration:
```
00:14:28.173 ERROR c.h.addon.imap.sync.ImapSynchronizer - Synchronization failed
java.lang.UnsupportedOperationException: Delete queries are not supported with enabled soft deletion. Use 'cuba.enableDeleteStatementInSoftDeleteMode' application property to roll back to legacy behavior.
        at com.haulmont.cuba.core.sys.QueryImpl.executeUpdate(QueryImpl.java:415) -[cuba-core-6.9.2.jar:6.9.2]
        at com.haulmont.addon.imap.dao.ImapMessageSyncDao.removeOldSyncs(ImapMessageSyncDao.java:196) -[imap-core-0.1-SNAPSHOT.jar:na]
        at com.haulmont.addon.imap.sync.ImapSynchronizer.synchronize(ImapSynchronizer.java:84) -[imap-core-0.1-SNAPSHOT.jar:na]
        at com.haulmont.addon.imap.sync.events.ImapStandardEventsGenerator.lambda$init$0(ImapStandardEventsGenerator.java:75) [imap-core-0.1-SNAPSHOT.jar:na]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) -[na:1.8.0_171]
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) -[na:1.8.0_171]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) -[na:1.8.0_171]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) -[na:1.8.0_171]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) -[na:1.8.0_171]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) -[na:1.8.0_171]
        at java.lang.Thread.run(Thread.java:748) -[na:1.8.0_171]
```

**Comment by oshiryaeva** [comment]
Why not upgrading the addon itself to 6.9?

**Comment by adhawan325** [comment]
I am experiencing the same issue.  I have upgraded the platform to 6.9-SNAPSHOT and the plugin to 1.1-SNAPSHOT.  Please see attached logs.
[app.log](https://github.com/cuba-platform/imap-addon/files/2281022/app.log)

Is there a way to fix this issue?

**Comment by shmelev-haulmont** [comment]
@adhawan325 could please specify name of the flag from your IMAP configuration (ImapMailbox.cubaFlag property) ?

**Comment by adhawan325** [comment]
ImapMailBox.authentication = Authentication
ImapMailBox.cubaFlag = Custom Flag
ImapMailBox.trashFolderName = Name of a folder to use as a trash bin
ImapMailBox.trashFolder = Trash Folder

**Comment by adhawan325** [comment]
value=9CRM

**Comment by adhawan325** [comment]
cuba-imap

**Comment by shmelev-haulmont** [comment]
@adhawan325 your issue is not related to the version of the platform or the plugin, it is due to the lack of support for custom IMAP flags on your server, see #68
