### ISSUE TITLE
Permanent Synchronization failed ERROR in Tomcat logs

### ISSUE THREAD

**Issue by oshiryaeva** [cuba-platform/imap-addon#71]
WTR
1. Create any working IMAP configuration, for example:
```
host: outlook.office365.com
port: 993
secure connection: SSL/TLS
user: cubatesting@outlook.com
password: remote236
```
2. Connect and save
3. Look at Tomcat logs and meditate

AR:
Emails are displayed in Message Browser, but there's a permanent error in logs that occurs approx. every 30 seconds:
```
2018-08-21 16:28:02.085 ERROR [ImapMailBoxFolderSynchronizationThread-3/imapSample-core/admin] com.haulmont.addon.imap.sync.ImapSynchronizer - Synchronization failed
java.lang.ClassCastException: java.lang.Integer cannot be cast to [Ljava.lang.Object;
 at com.haulmont.addon.imap.dao.ImapDao.findLastMessageNumber(ImapDao.java:80) ~[imap-core-1.1-SNAPSHOT.jar:na]
 at com.haulmont.addon.imap.sync.ImapFlaglessSynchronizer.handleNewMessages(ImapFlaglessSynchronizer.java:50) ~[imap-core-1.1-SNAPSHOT.jar:na]
 at com.haulmont.addon.imap.sync.ImapSynchronizer.synchronize(ImapSynchronizer.java:99) ~[imap-core-1.1-SNAPSHOT.jar:na]
 at com.haulmont.addon.imap.sync.events.ImapStandardEventsGenerator.lambda$null$1(ImapStandardEventsGenerator.java:85) [imap-core-1.1-SNAPSHOT.jar:na]
 at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_101]
 at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) ~[na:1.8.0_101]
 at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) ~[na:1.8.0_101]
 at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) ~[na:1.8.0_101]
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_101]
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_101]
 at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_101]
```

ER:
Successful synchronization, no errors in logs

**Comment by oshiryaeva** [comment]
On the application startup, warnings are logged for each saved configuration:
```
2018-08-22 15:24:37.505 WARN [Initial-sync-mailbox#c7cd2d03-e6ac-8ae6-96df-b091635821df] com.haulmont.addon.imap.sync.events.ImapStandardEventsGenerator - Exception while shutting down sync task for mailbox#c7cd2d03-e6ac-8ae6-96df-b091635821df
java.lang.InterruptedException: null
 at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2067) ~[na:1.8.0_101]
 at java.util.concurrent.ThreadPoolExecutor.awaitTermination(ThreadPoolExecutor.java:1465) ~[na:1.8.0_101]
 at java.util.concurrent.Executors$DelegatedExecutorService.awaitTermination(Executors.java:675) ~[na:1.8.0_101]
 at com.haulmont.addon.imap.sync.events.ImapStandardEventsGenerator.lambda$init$2(ImapStandardEventsGenerator.java:95) ~[imap-core-1.1-SNAPSHOT.jar:na]
 at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_101]
 at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_101]
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_101]
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_101]
 at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_101]
```
