### ISSUE TITLE
Email does not appear in the new folder after moving

### ISSUE THREAD

**Issue by zhenyazb** [cuba-platform/imap-addon#78]
CUBA Platform 7.0.0
Add-on 1.3-SNAPSHOT

1. Set `cuba.schedulingActive` in `true` in the *Application properties* screen
2. Create scheduled task for IMAP
2. Create configuration in the *IMAP Configuration* screen
3. Check two folders for synchronization
4. Save configuration
5. Move message from one folder to another in the email box

Expected result: message moved from one folder to another in the *IMAP Message Browser*
Actual result: message disappeared from one folder but not appeared in another

**Comment by zhenyazb** [comment]
Error while trying to view moved message

1. Move message from one folder to another in the email box
2. Open *IMAP Message Browser*

Expected result: message moved, flags are displayed
Actual result: message moved, flags are disappeared

3. Choose the message in the list and click the *View* button.

Expected result: the message is displayed
Actual result: progress bar is moving, *IMAP Message Browser -> Email* screen is empty, error occurs in logs 

```
Exception in com.haulmont.cuba.web.AppUI: 
java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) [na:1.8.0_191]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) [na:1.8.0_191]
	at com.vaadin.server.VaadinSession$FutureAccess.get(VaadinSession.java:102) ~[vaadin-server-8.6.4-6-cuba.jar:8.6.4-6-cuba]
	at com.vaadin.server.VaadinService.runPendingAccessTasks(VaadinService.java:2021) [vaadin-server-8.6.4-6-cuba.jar:8.6.4-6-cuba]
	at com.vaadin.server.VaadinSession.unlock(VaadinSession.java:1007) [vaadin-server-8.6.4-6-cuba.jar:8.6.4-6-cuba]
	at com.vaadin.server.VaadinService.ensureAccessQueuePurged(VaadinService.java:1983) [vaadin-server-8.6.4-6-cuba.jar:8.6.4-6-cuba]
	at com.vaadin.server.VaadinService.accessSession(VaadinService.java:1949) [vaadin-server-8.6.4-6-cuba.jar:8.6.4-6-cuba]
	at com.vaadin.server.VaadinSession.access(VaadinSession.java:1406) [vaadin-server-8.6.4-6-cuba.jar:8.6.4-6-cuba]
	at com.vaadin.ui.UI.access(UI.java:1529) [vaadin-server-8.6.4-6-cuba.jar:8.6.4-6-cuba]
	at com.haulmont.cuba.web.gui.executors.impl.WebBackgroundWorker$WebTaskExecutor$1.done(WebBackgroundWorker.java:186) [cuba-web-7.0.2.jar:7.0.2]
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:384) [na:1.8.0_191]
	at java.util.concurrent.FutureTask.set(FutureTask.java:233) [na:1.8.0_191]
	at java.util.concurrent.FutureTask.run(FutureTask.java:274) [na:1.8.0_191]
	at com.haulmont.cuba.web.gui.executors.impl.WebBackgroundWorker$WebTaskExecutor.lambda$startExecution$1(WebBackgroundWorker.java:376) [cuba-web-7.0.2.jar:7.0.2]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_191]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_191]
Caused by: java.lang.NullPointerException: null
	at com.haulmont.addon.imap.web.imapmessage.ImapMessageEdit$InitBodyTask.done(ImapMessageEdit.java:125) ~[imap-web-1.3-SNAPSHOT.jar:na]
	at com.haulmont.addon.imap.web.imapmessage.ImapMessageEdit$InitBodyTask.done(ImapMessageEdit.java:102) ~[imap-web-1.3-SNAPSHOT.jar:na]
	at com.haulmont.cuba.web.gui.executors.impl.WebBackgroundWorker$WebTaskExecutor.handleDone(WebBackgroundWorker.java:280) [cuba-web-7.0.2.jar:7.0.2]
	at com.haulmont.cuba.web.gui.executors.impl.WebBackgroundWorker$WebTaskExecutor$1.lambda$done$0(WebBackgroundWorker.java:187) [cuba-web-7.0.2.jar:7.0.2]
	at com.vaadin.ui.UI.accessSynchronously(UI.java:1468) [vaadin-server-8.6.4-6-cuba.jar:8.6.4-6-cuba]
	at com.vaadin.ui.UI$3.run(UI.java:1532) ~[vaadin-server-8.6.4-6-cuba.jar:8.6.4-6-cuba]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_191]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_191]
	at com.vaadin.server.VaadinService.runPendingAccessTasks(VaadinService.java:2018) [vaadin-server-8.6.4-6-cuba.jar:8.6.4-6-cuba]
	... 13 common frames omitted
```
